### ISSUE TITLE
Flickering white dots and lines on texture seams

### ISSUE THREAD

**Issue by LDS1** [SaiyansKing/GD3D11#10]
The effect is much more severe than I was able to capture on screenshot.
White dots are running down the texture seams pretty fast, looks like flickering. 
Especially visible in dark environments. 
![Screen Shot 2021-12-08 at 1 39 07 AM](https://user-images.githubusercontent.com/8604295/145127443-84c7a7e4-f986-41db-a02f-e8c5eac59f19.jpeg)

**Comment by SaiyansKing** [comment]
Those dots appears due to fog being enabled. Probably something is wrong in the height fog shader.
I'll try to something about it but I don't promise anything.

**Comment by postm1** [comment]
If it appears on the edge of the mesh it is a bad geometry (a hole, for example)

**Comment by SaiyansKing** [comment]
Yes, it is due to bad geometry, the polygons doesn't connect correctly and sometimes you can see holes because of that.
Because height fog works by using depth buffer those pixels always get determined as farest points that can be from the camera which result in white dots.

Fun fact: jumping through those holes can thrown your character in air because there can't be determined floor position.

**Comment by agris-codes** [comment]
This is rampant all over the mod. You can also see what I presume are alpha texture seams from book overlays on every book that I've encountered in Chapter 1. Not sure if recipes and other similar textures have the same issue.

**Comment by InfamouslyJaded** [comment]
Just wanted to add that disabling fog doesn't seem to prevent this issue completely, it makes it more berable but those dots can still appear, most often when turning the camera.

**Comment by InfamouslyJaded** [comment]
![image](https://user-images.githubusercontent.com/79400302/146553252-1365e71f-a11b-48bb-b33e-3d5cf8cce36c.png)
Here's an example of that, there's one right above my cursor.

**Comment by InfamouslyJaded** [comment]
Something interesting I noticed is that when you have the F11 or Ctrl + F11 menus open they don't flicker, if there's a dot there it stays there if there's no dot then none will appear, it seems like everything can move around in that 'mode' except for the player character, maybe adding a switch to enter that mode but still be able to move around could be a decent band-aid solution?

**Comment by SaiyansKing** [comment]
> Just wanted to add that disabling fog doesn't seem to prevent this issue completely, it makes it more berable but those dots can still appear, most often when turning the camera.

Since it is a hole because polygons doesn't connect correctly what do you expect? Sky dome needs to be rendered too so with disabled fog you will see sky dome through the holes.

> Something interesting I noticed is that when you have the F11 or Ctrl + F11 menus open they don't flicker, if there's a dot there it stays there if there's no dot then none will appear, it seems like everything can move around in that 'mode' except for the player character, maybe adding a switch to enter that mode but still be able to move around could be a decent band-aid solution?

It don't flicker because the camera is in fixed place, you can't play like that.

**Comment by LDS1** [comment]
can't reproduce in dev5
