### ISSUE TITLE
Lens glare around torches 

### ISSUE THREAD

**Issue by LDS1** [SaiyansKing/GD3D11#12]
![Screen Shot 2021-12-08 at 3 43 50 AM](https://user-images.githubusercontent.com/8604295/145137277-559812e2-45e5-4fd6-a9b1-1b1fbeae044b.jpeg)

**Comment by postm1** [comment]
That is not a visual bug. That is a flat texture. It can be removed via changing ZEN file (map)

**Comment by LDS1** [comment]
@SaiyansKing please close the ticket if it's not dx11 related.

**Comment by SaiyansKing** [comment]
Yes, it is flat texture(decal) that is always aligned to the camera, only way to do something about it is to edit ZEN file.
