### ISSUE TITLE
PFX Blend Mode

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#13]
Hi, is there a way to impement BLEND mode in PFX (particles render) ?
Pfx has an option visAlphaFunc_s which has options:

zRND_ALPHA_FUNC_BLEND,
zRND_ALPHA_FUNC_ADD,

ADD works fine I guess, but BLEND option does not work.
That is a big problem with any visual effects. They don't look like they should be.

Example: Left (dx7), Right (dx11), the pfx should be black, not white. The alpha function is BLEND;
![124604120-4bd83d00-de73-11eb-9a0a-6659ef6196db](https://user-images.githubusercontent.com/2078377/145210646-9d04962a-a0ac-42b3-9267-e2f63e89bc58.jpg)

**Comment by SaiyansKing** [comment]
Currently working on it and most likely will add rendering sphere models for visuals too.

**Comment by postm1** [comment]
Thanks! Waiting for it

**Comment by postm1** [comment]
So, it works now.
