### ISSUE TITLE
Black screen or crash

### ISSUE THREAD

**Issue by JackStormSword** [SaiyansKing/GD3D11#16]
Doesn't seem to work for the first game, works great for 2nd game. After cutscene game either crashes or stay on a black screen with music playing. I'm using fresh steam install with dev33 unzipped in Gothic\system directory.

**Comment by SaiyansKing** [comment]
Can you give some information about your hardware? If you're using Intel HD then keep in mind that the GD3D11 renderer doesn't work correctly with those integrated gpu's.

When the game crashes does it come with access violation or assertion failed? If yes can you make a screenshot of it or copy the error here?

Did you test the game if it does work at all without the renderer?
There should be Log.txt file in Gothic\system directory can you post it here(it might give some insight on the problem)?

**Comment by JackStormSword** [comment]
1. i7 1080ti 32gb ram win10 also tested today on my laptop and same black screen r7 5800h 3080 32gb ddr4 win10.
2. When it did crash it didn't come with access violation or any error window but most of the time it's just black screen with music playing.
3. I did test the game after fresh steam install and it runs good. I also tested out different versions. dev33 and dev25 both have black screen for me, I thought that maybe it was due to versions combining but no dev25 also has black screen.
4. If I disable Animate Static Vobs I can see the game for a second but then it just goes back to black screen.
5. I went back to dev20 and that is working perfectly fine without any issues, crashes or black screen.
6. I tried to use dev21 and that worked, so I tried to find exact version where it started and dev22 works fine but dev23 I was met with black screen and then game crashes everytime and dev24 game just stays in a black screen.
7. So whatever changed between dev22 and dev23 is causing the problem. Below I have provided log files for every version, hope it helps. Also provided a screenshot that dx11 is running but game is just a black screen.
![dx11 black screen](https://user-images.githubusercontent.com/95876373/145492699-a3dde769-aa6b-4703-a7b8-0533cdf27da4.PNG)
[Log dev23.txt](https://github.com/SaiyansKing/GD3D11/files/7689104/Log.dev23.txt)
[Log dev24.txt](https://github.com/SaiyansKing/GD3D11/files/7689106/Log.dev24.txt)
[Log dev33.txt](https://github.com/SaiyansKing/GD3D11/files/7689107/Log.dev33.txt)

**Comment by JackStormSword** [comment]
Dev22 ran from spawn to the old camp, no crashes no black screen. Log has some "Warning:" in them I don't know if that's normal or errors that will make the game crash after a while
[Log dev22.txt](https://github.com/SaiyansKing/GD3D11/files/7689189/Log.dev22.txt)
.

**Comment by SaiyansKing** [comment]
Shoulde be working in dev34, there was some problem with the borrowed morph mesh glitch fix and the patch was removed.

**Comment by JackStormSword** [comment]
Dev34 is working great, thank you for fixing this problem and updating my favorite game for everybody to enjoy.
