### ISSUE TITLE
Verify checksum of GothicMod.exe for G2

### ISSUE THREAD

**Issue by dosinabox** [SaiyansKing/GD3D11#18]
I use Gothic2.exe renamed for GothicMod.exe and custom GothicStarter.exe renamed to Gothic2.exe in **Gothic 2 Steam Fix**:
https://github.com/dosinabox/g2_steam_fix
https://steamcommunity.com/sharedfiles/filedetails/?id=757500304

It allow to use mod starter when launching game from Steam, but players with GD3D11 receive the following message which confuse them a lot:
<img width="718" alt="Screenshot_1" src="https://user-images.githubusercontent.com/39790055/145684075-b09dfc14-f255-45a1-a1a6-d77025f514f2.png">

It would be great if you also verify checksum of GothicMod.exe even for G2. The game itself runs GD3D11 fine without problems, since GothicMod.exe is  just renamed Gothic2.exe (2.6 with or without LAA hack, depending on install options).

**Comment by dosinabox** [comment]
Here's the changes to GothicStarter.exe: https://github.com/dosinabox/g2_steam_fix/commit/77e56fa64d43ae2200f8cecedde38ea81fb4c0e6
All because Steam version use only Gothic2.exe as default executable and simple rename of GothicStarter.exe won't help.

**Comment by SaiyansKing** [comment]
I'll remove the checksum check in next version since it isn't needed due to mechanism that detect Gothic version.

**Comment by dosinabox** [comment]
Thank you!
