### ISSUE TITLE
Why does Gothic 1 with this dx11 renderer look so different than vanilla Gothic 1?

### ISSUE THREAD

**Issue by Kologn** [SaiyansKing/GD3D11#24]
I've noticed that in the old camp when you watch into the sky you can see lightning bolts which you cannot see in vanilla gothic 1, right? Is this just an illusion or is this dx11 renderer changing a bit too much?

**Comment by LDS1** [comment]
Colony is fully covered with lightning dome. It's visible for some time and most of the time is hidden, as long as I remember. 

Please convert it to discussion if there is no bug.

**Comment by Kologn** [comment]
Okay, thanks.
