### ISSUE TITLE
please enable gothic1 renderer binary output for all tags

### ISSUE THREAD

**Issue by stefson** [SaiyansKing/GD3D11#26]
hey there, 

thank you for all your hard work which recently got pulled back into kiridis his fork, it fixed two major bugs in the Gothic2 renderer for me.

unfortunatley, it caused a regression in the Gothic1 renderer, and it will be tricky to find the breaking commit through a binary search, as 17.7-dev25 is the last of your tags with the Gothic1 binary attached. 

so can you maybe reenable the Gothic1 renderer binary build for all tags, please? 

thank you

**Comment by SaiyansKing** [comment]
I don't know what exactly you mean, from dev26 it is packed in a way that you don't need to download version for Gothic1/Gothic2 non-AVX/AVX as it is detected by `ddraw.dll` that act as a proxy.
The binaries are still there in `GD3D11\Bin` folder, you can copy for example `g1.dll` or `g1_avx.dll` to the main `system` folder and rename it as `ddraw.dll`.

**Comment by stefson** [comment]
that's a level of sophistication that was not obvious to me. thank you for your swift answer.
