### ISSUE TITLE
SpacerNet help vobs + alpha textures

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#30]
Hi, I use Dx11 when I create locations in Spacer.NET
And I have a little problem. When I toggle "show help vobs" (like waypoints, freepoints), alpha textures does not render properly on other vobs. (like on screen).
![spacerNet](https://user-images.githubusercontent.com/2078377/146733835-eb0a56eb-27b6-4bbd-8f34-db8898bdc139.JPG)

Of course, **I don't ask you to create a special build for me**, but it there a way to fix it? May be some little change it the code?
Vobs are rendered in D3D11GraphicsEngine::DrawVOBsInstanced()
That code below renders help vobs, but distorts usual vobs with alpha textures.
![image](https://user-images.githubusercontent.com/2078377/146734230-96e2adc7-07c9-4c1e-ac58-13d0193360cb.png)

I would be glad if you tell me what to change to fix that stuff (I can build it for myself)

**Comment by SaiyansKing** [comment]
If you want to use alpha test then changing `PS_Diffuse` pixel shader to `PS_DiffuseAlphatest` should be enough.
If you want them to be rendered with an actual transparency then you need to schedule them to different stage of rendering then render them using appropriate blending mode and pixel shader, rendering objects with transparency at gbuffer rendering stage would result in some crappy glitches.

**Comment by postm1** [comment]
I only need to render help vobs (without transparency), but rendering help vobs create such bug for other vobs. Ok, I will try.

**Comment by postm1** [comment]
Thanks, it worked, can you add it in the actual code?
Change PS_Diffuse to PS_DiffuseAlphatest in the code I gave you above on the screen.

![image](https://user-images.githubusercontent.com/2078377/147096153-5a217767-8922-4699-ade3-ac95e8d79089.png)
This code does not affect the game cause it is compiled only for spacer.

**Comment by postm1** [comment]
I close the topic, the problem solved ;)
