### ISSUE TITLE
CoM rare black screen issue

### ISSUE THREAD

**Issue by Kilrha** [SaiyansKing/GD3D11#42]
Very rarely the screen just goes black and I have to restart the game to fix it.
UI elements still work like the health/mana bars, inventory and pause menu.
I use the renderer with pretty much everything maxed out except for view distance and tesselation turned off.

**Comment by SaiyansKing** [comment]
Hi,
I'm sorry but it doesn't have to do anything with GD3D11 renderer, it is their fadeout effect that sometimes gets bugged and it happens without renderer too. In fact the "black screen" are always drawed only with the exception that most of time it is drawed with transparency set as "0" so it is completely invisible(you can check it using RenderDoc).

**Comment by Kilrha** [comment]
ok thanks for the response. I'll try contacting the CoM devs about patching this.
