### ISSUE TITLE
No mouse cursor when I open DX11 menu

### ISSUE THREAD

**Issue by ZekTran** [SaiyansKing/GD3D11#43]
After launching the DX11 configuration menu, I am unable to set options due to the lack of a cursor and any ability to enable it. Is there any way to fix this? I try to delete DX11 files from the folder and put it again, check for verification of game files etc.

**Comment by SaiyansKing** [comment]
Hi,
most of the mouse problems are from the System Pack(especially the Union Mouse Wrapper). I've recently added the requested Ikarus bindings for the so called compatibility with Union and plugins(even though I was reluctant) and most of mouse cursor visibility problems appeared at that time. Can you check if the mouse cursor works correctly with [v17.7-dev34](https://github.com/SaiyansKing/GD3D11/releases/tag/v17.7-dev34) version?

If you're using Steam version they also added the DirectInputTo8 wrapper that I've checked sometime ago and it was messing with mouse cursor visibility so you might consider deleting the dinput.dll wrapper.

**Comment by ZekTran** [comment]
Thank you for help. It works on [v17.7-dev34](https://github.com/SaiyansKing/GD3D11/releases/tag/v17.7-dev34).

**Comment by SaiyansKing** [comment]
You most likely used SpacerNET version which have different mouse controls.
