### ISSUE TITLE
Remove from release

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#50]
Can you remove SpacerNet build from release or rename the first one. Many users download spacernet build for an usual game and got some errors. Or rename both to better understanding what is for game and what is for editing.

![image](https://user-images.githubusercontent.com/2078377/151301213-1c84fb13-39b5-470a-80e2-d6fdc2d32bd2.png)

**Comment by SaiyansKing** [comment]
Removed, looks like the SpacerNET version needs special place for download(renaming them probably wouldn't be enough) xD
