### ISSUE TITLE
transparency issues on some surfaces

### ISSUE THREAD

**Issue by stefson** [SaiyansKing/GD3D11#52]
hey there,

I'm playing Gothic2 Mod Odysee 2.6.4 with your fork of the renderer, and noticed a wall which is transparent. I highly doubt this is rendered correctly: 

![2022-01-30-221024_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/151718190-ea986067-6477-4342-bb58-0cbef05f8e8c.png)

I will attach a savegame, where the character is right in front of the wall: [savegame1.zip](https://github.com/SaiyansKing/GD3D11/files/7966932/savegame1.zip)

Mod can be loaded from here: https://www.worldofgothic.de/dl/download_522.htm ; there is an english version available if you need it.

**Comment by stefson** [comment]
here is another texture that has transparency issues: 

![2022-02-05-135055_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/152642967-90e2b75c-83bc-4c0a-9eb8-d2ca5ad5ffcc.png)

its with the same Mod (Odysee 2.6.4), here is a savegame

[savegame1.zip](https://github.com/SaiyansKing/GD3D11/files/8008044/savegame1.zip)

**Comment by SaiyansKing** [comment]
Hi, it isn't exactly GD3D11 renderer fault but for some reason in this mod those polygons material are marked as `zMAT_GROUP_WATER` and because of that they are rendered using the water pixel shader instead of solid pixel shader. Can't do anything about that from renderer side.
