### ISSUE TITLE
Rendering world mesh visual bug

### ISSUE THREAD

**Issue by postm1** [SaiyansKing/GD3D11#64]
Hi, when Dx11 gets polygons for rendering there is a visual "bug". 
For example, far polygons of sand (below water) are not rendered properly. I guess some polygons are rejected. And we have this:
![image](https://user-images.githubusercontent.com/2078377/170824485-ef1a3251-287a-45fd-abd3-485041c9b1da.png)
It does not look good when you seen over ocean. 
If you increase World Draw Distance to 10 is helpes sometimes, but not every time, cause at bigger distances you have the same bug anyway. 
I guess the problem is in fetching polygons for rendering.

I think DX11 gets the center of a polygon and if it has huge size it is not drawn, example: hero is near the poly, but it is not rendered due its size.
![image](https://user-images.githubusercontent.com/2078377/170831916-ef4b8aae-2a62-4a47-b3e3-453a7113fa36.png)

**Comment by postm1** [comment]
I think render should check all points of polygon for nearest point and only after that check distance to it ;)

**Comment by postm1** [comment]
Checked, I increase SectionDrawRadius in 10 times (to prove a problem for myself) and there is no problem, so I guess you can fix it easily, somehow...
![image](https://user-images.githubusercontent.com/2078377/170832813-77c43ffe-8bc2-4fd4-b3ba-d1e702cf6c9f.png)

**Comment by postm1** [comment]
The most easiest way to fix this problem - allow user to increate SectionDrawRadius up to 20, I tries, at 15+ it works fines on all maps ;)

**Comment by SaiyansKing** [comment]
Hi,
I have increased maximum world draw distance to 20 for now, I'll experiment with making it to draw any section that have intersection with drawing distance but it most likely will decrease performance in some cases.

**Comment by postm1** [comment]
Yes, that stuff could be created as an option, and to performance problem ;)
