### ISSUE TITLE
WATERFALL BUG

### ISSUE THREAD

**Issue by GrImIz1** [SaiyansKing/GD3D11#67]
CAN YOU FIX THIS AT THE WATERFALL

https://steamcommunity.com/sharedfiles/filedetails/?id=2812279717

MOD IS CALLED GOTHIC 1 DICCURIC

**Comment by GrImIz1** [comment]
can you fix this

**Comment by GrImIz1** [comment]
can you fix this

**Comment by SaiyansKing** [comment]
Hi, this "bug" is unfixable because Gothic 1 doesn't have required information for polygons, the only way to semi-fix it is to disable water shader entirely and without this shader the water will be looking even worse than in original DX7 due to lacking of lighting calculations.

**Comment by GrImIz1** [comment]
how to disable water shader
