### ISSUE TITLE
Spacer.net - brak myszki po zainstalowaniu Dx11

### ISSUE THREAD

**Issue by Merkuless** [SaiyansKing/GD3D11#68]
Mam pewien problem po wgraniu DX11 do Gothica ze Spacer.net, gdy włączę go bez DX11 kursor myszy wyświetla się normalnie  i mogę sobie działać, a po wgraniu DX'a kursor staje się niewidoczny i nie idzie w zasadzie nic zrobić :/

**Comment by SaiyansKing** [comment]
Witam, nie wiem jak działa DX11 w spacer.NET bo się tym nie zajmuje ale potrzebujesz specjalnego builda do tego. U mnie takowego nie znajdziesz więc zostaje ci pobrać go z repozytorium Kiridesa albo z dysku Likera gdzie jest spacer.NET.

Co do tego czemu u mnie nie ma builda do spacer.NET to możesz podziękować ludziom którzy nie używają mózgu i wrzucają go do normalnego Gothica przez co potem zgłaszają błędy których nie ma.
