### ISSUE TITLE
Gothic 1 with Union 1.0m crashed when closing F11 menu

### ISSUE THREAD

**Issue by lucifer602288** [SaiyansKing/GD3D11#72]
Gothic 1 with Union 1.0m crashed when closing F11 menu, issue is not with Union 1.0l and Gothic 2 works fine:

======================================= UNHANDLED EXCEPTION OCCURED ======================================================
======================================= CRASH INFOS: =====================================================================
GOTHIC 1.08k_mod, Parser Version: 50
User:  KB,  CPUType: 586,  Mem: 0 MB total, 0 MB free
Startup Options:
=============================================== CALLSTACK : ==============================================================
0023:00000000 (0x00000010 0x0126F7A4 0x0126F788 0x004C7EEB) G1.exe

**Comment by FakeMichau** [comment]
1.0m with Gothic 2 works for me.
Did you use 1.0m v2?

**Comment by lucifer602288** [comment]
Yes, Union 1.0m 26.06.2022 v2.

**Comment by lucifer602288** [comment]
Problem found it was the plugin GRawInput-1.4 which seems not to be completly compatible with Gothic 1.
Problem occurred when F11 window closes and switches back to gothic input.
