### ISSUE TITLE
Invisisble Enemies & Player

### ISSUE THREAD

**Issue by Josko91** [SaiyansKing/GD3D11#81]
Sometimes the player or enemies can become completely invisible, this dosn't happend so often but it does happen time to time. Only thing that fixes it is actually saving the game, just saving, don't need to load game. But it can happend again, so saving is just a quick fix, not a permanent fix.

I'm using the Steam Workshop renderer.

It seems to happend randomly, I don't think anything specific triggers the bug.

**Comment by SaiyansKing** [comment]
> I'm using the Steam Workshop renderer.

I'm not responsible for the renderer that has been posted on Workshop since it wasn't posted by me there, this bug shouldn't be happening if you manually download the latest renderer.

**Comment by Josko91** [comment]
I thought the renderer on workshop was updated to the latest version, I'll try to manually download latest from here then =)

**Comment by Josko91** [comment]
The workshop one is updated to v17.8-dev7, is that the latest? On this site it says v17.8-dev4 instead

Not sure which one is latest
