### ISSUE TITLE
selected inventory items have a green lining around two of their four corners

### ISSUE THREAD

**Issue by stefson** [SaiyansKing/GD3D11#96]
hey there, I'm struggeling a little bit with describing this little bug I just noticed. 

So in Gothic 2 night of the Raven, there is the item menu which you access via <TAB> to scroll around in your inventory. If you look closely, you see a very fine hue of light green drawn around two of their four courners, if that item was selected to wear - it has a dard red background if selected. So its for rings, runes and other gear like harnish and belts: 

 ![2022-12-27-114207_1680x1050_scrot](https://user-images.githubusercontent.com/14232936/209664611-3164e001-8417-4e24-befc-9345fa8be10d.png)

I'm using Amd RX 570, and the Gold Version of Gothic2, Patchversion 2.7
The render is your fork with the tag `17.8-dev9` https://github.com/SaiyansKing/GD3D11/releases/tag/v17.8-dev9

I'm almost certain that this is a regression which wasn't present around a year ago (last time I played extensivly with the renderer) - what do you think?

**Comment by SaiyansKing** [comment]
If you mean the active item dark-red box then everything is how it should be. Here is how this texture looks that is rendered when item is active:
![image](https://user-images.githubusercontent.com/38609240/209757209-3c717b10-061d-408b-9e67-9aa41379d524.png)

Maybe you were playing with texture packs previously?

**Comment by stefson** [comment]
Indeed, I vaguely remember using some sort of texture pack. I reinstalled from scratch a few days ago on a new system. 

Should I close the issue then?

**Comment by stefson** [comment]
So I can confirm this is normal, or an application bug. Using a texture pack (riisis) will provide an alternative texture. Thank you for the hint.
